name: Release app

on:
    workflow_dispatch:

jobs:
    build:
        strategy:
            matrix:
                os:
                    [
                        { name: "linux", image: "ubuntu-latest" },
                        { name: "windows", image: "windows-latest" },
                        { name: "macos", image: "macos-latest" },
                    ]
        runs-on: ${{ matrix.os.image }}
        timeout-minutes: 10
        steps:
            - name: Github checkout
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x
            - run: npm install
            - name: Debug token
              run: echo ${GITHUB_TOKEN:0:5}
              env:
                  GITHUB_TOKEN: ${{ secrets.ELECTRON_FORGE_GITHUB_TOKEN }}
            - name: Publish app
              env:
                  GITHUB_TOKEN: ${{ secrets.ELECTRON_FORGE_GITHUB_TOKEN }}
              run: npm run publish-app
